spring.application.name=officeApp

spring.datasource.url=jdbc:postgresql://localhost:5432/office
spring.datasource.username=officeapp
spring.datasource.password=officeapp
spring.datasource.driver-class-name=org.postgresql.Driver




spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations
spring.flyway.clean-disabled=true